### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by nashio** [stevearc/gkeep.nvim#7]
**Describe the bug**
When executing Gkeeplogin and entering credentials, I'm redirected to the browser and see "one moment please..." forever.
checking the url I see this "auth_display_name=Android+Login+Service&source=Android+Login" but I'm using a macbook, not sure if this is expected.

**To Reproduce**
- install,
:UpdateRemotePlugins
:Gkeeplogin

2. Run command '....'

**Expected behavior**
to actually login

**Version information**
 - OS: macos catalina
 - Neovim: NVIM v0.6.0
 - Gkeep: [output of `:checkhealth gkeep`]
``` 
## gkeep                                                                                                                                                     
  - OK: gkeepapi 0.13.7 installed                                                                                                                            
  - OK: keyring installed                                                                                                                                    
  - WARNING: Not logged in                                                                                                                                   
    - ADVICE:                                                                                                                                                
      - Try :GkeepLogin       
```
**Additional context**

**Screenshots**

**Comment by stevearc** [comment]
The android stuff in the url should be fine, it's just the underlying python libraries impersonating an android app to get API access.

The browser redirect happens when Google thinks the login is suspicious or needs some additional confirmation. Some variation of trouble with this flow has been reported on the underlying gpsoauth library (see https://github.com/simon-weber/gpsoauth/issues/37), with a suggested workaround of using https://accounts.google.com/DisplayUnlockCaptcha if the browser flow fails.

**Comment by nashio** [comment]
Thanks for responding. I tried DIsplayUnlockCaptcha but when trying to log in again same thing happen. Or maybe I'm not following what I should be doing in which order.

**Comment by nashio** [comment]
oh, or maybe I should be using an app specific password instead. Will try that

**Comment by stevearc** [comment]
What's the full domain name of the url opened in the browser? And if you open the developer console are there any errors present? As far as I remember, it *should* just be a google oauth landing page, so it's very strange that it's not loading. If you're using a google workspace account it's possible you'll have a different oauth landing page that could be experiencing problems.

If you're using 2-factor, you *will* need to supply an app password (as mentioned [in the README](https://github.com/stevearc/gkeep.nvim/#setup)). If you have 2-factor enabled and haven't been doing that I'd be curious to know, because this failure mode is terrible and I should document it to warn others.

**Comment by nashio** [comment]
So app specific pwd worked well thx. The only thing I see is that when I navigate to "Home" I get this error.
```

Error detected while processing function _gkeep_menu_action[1]..remote#define#request:                                                                       
line    2:                                                                                                                                                   
Error invoking '/Users/code/configs/.config/nvim/bundle/gkeep.nvim/rplugin/python3/gkeep:function:_gkeep_menu_action' on channel 3 (python3-rp
lugin-host):                                                                                                                                                 
error caught in request handler '/Users/code/configs/.config/nvim/bundle/gkeep.nvim/rplugin/python3/gkeep:function:_gkeep_menu_action [['selec
t']]':                                                                                                                                                       
Traceback (most recent call last):                                                                                                                           
  File "/Users/code/configs/.config/nvim/bundle/gkeep.nvim/rplugin/python3/gkeep/plugin.py", line 46, in d                                    
    return f(self, *args[0])                                                                                                                                 
  File "/Users/code/configs/.config/nvim/bundle/gkeep.nvim/rplugin/python3/gkeep/plugin.py", line 80, in w                                    
    f(self, *args, **kwargs)                                                                                                                                 
  File "/Users/code/configs/.config/nvim/bundle/gkeep.nvim/rplugin/python3/gkeep/plugin.py", line 349, in menu_action                         
    self._menu.action(action, *args)                                                                                                                         
  File "/Users/code/configs/.config/nvim/bundle/gkeep.nvim/rplugin/python3/gkeep/views/view.py", line 119, in action                          
    getattr(self, meth)(*args)                                                                                                                               
  File "/Users/code/configs/.config/nvim/bundle/gkeep.nvim/rplugin/python3/gkeep/views/menu.py", line 226, in cmd_select                      
    self._notelist.set_query(item.query)                                                                                                                     
  File "/Users/code/configs/.config/nvim/bundle/gkeep.nvim/rplugin/python3/gkeep/views/notelist.py", line 92, in set_query                    
    self.render()                                                                                                                                            
  File "/Users/code/configs/.config/nvim/bundle/gkeep.nvim/rplugin/python3/gkeep/views/notelist.py", line 128, in render                      
    render_note_list(self._vim, self._config, self._api, bufnr, self.notes)                                                                                  
  File "/Users/code/configs/.config/nvim/bundle/gkeep.nvim/rplugin/python3/gkeep/views/view_util.py", line 98, in render_note_list            
    buf[:] = lines                                                                                                                                           
  File "/usr/local/lib/python3.9/site-packages/pynvim/api/buffer.py", line 65, in __setitem__                                                                
    return self.request('nvim_buf_set_lines', start, end, False, lines)                                                                                      
  File "/usr/local/lib/python3.9/site-packages/pynvim/api/common.py", line 58, in request                                                                    
    return self._session.request(name, self, *args, **kwargs)                                                                                                
  File "/usr/local/lib/python3.9/site-packages/pynvim/api/nvim.py", line 182, in request                                                                     
    res = self._session.request(name, *args, **kwargs)                                                                                                       
  File "/usr/local/lib/python3.9/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request                                                          
    raise self.error_wrapper(err)                                                                                                                            
pynvim.api.common.NvimError: String cannot contain newlines
```

**Comment by stevearc** [comment]
Glad the login is working! I'll add some documentation about this so hopefully other people won't get burned by it.

For the current issue, my guess is that you have a note with newlines in the title. I thought I'd handled that because I ran into it myself earlier, but apparently something slipped through. I'm going to sleep soon and will be traveling all of tomorrow, but I'll revisit this on the weekend and get a fix.

**Comment by nashio** [comment]
awesome thanks. Btw this plugin is a great idea, lmk where I can drop a "buy you coffee" donation

**Comment by stevearc** [comment]
The crash should be fixed now

I'm glad you like it! I appreciate the thought, but I have some hangups
about accepting money for my open source work. I may change my mind at some
point, but for now the only thanks I need is that someone finds the project
useful 🙂
