### ISSUE TITLE
Failed to login: Failed to create the collection: Prompt dismissed..  

### ISSUE THREAD

**Issue by ruanyouxing** [stevearc/gkeep.nvim#8]
**Describe the bug**
Failed to login 
Error log last line is: 'keyring.errors.InitError: Failed to create the collection: Prompt dismissed..'

**To Reproduce**
1.Install plugin and execute :UpdateRemotePlugins
2. run :GkeepLogin 
3.See error:
```Error detected while processing function _gkeep_prompt_close[1]..remote#define#request:
line    2:
Error invoking '/home/hungz/.local/share/nvim/site/pack/packer/start/gkeep.nvim/rplugin/python3/gkeep:function
:_gkeep_prompt_close' on channel 3 (python3-rplugin-host):
error caught in request handler '/home/hungz/.local/share/nvim/site/pack/packer/start/gkeep.nvim/rplugin/pytho
n3/gkeep:function:_gkeep_prompt_close [['hungzucced']]':
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/secretstorage/util.py", line 46, in send_and_get_reply
    return self._connection.send_and_get_reply(msg, unwrap=True)
  File "/usr/lib/python3.10/site-packages/jeepney/io/blocking.py", line 190, in send_and_get_reply
    return unwrap_msg(msg_in)
  File "/usr/lib/python3.10/site-packages/jeepney/wrappers.py", line 214, in unwrap_msg
    raise DBusErrorResponse(msg)
jeepney.wrappers.DBusErrorResponse: [org.freedesktop.DBus.Error.UnknownMethod] ('Object does not exist at path
 “/org/freedesktop/secrets/collection/login”',)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/lib/python3.10/site-packages/secretstorage/collection.py", line 161, in get_default_collection
    return Collection(connection)
  File "/usr/lib/python3.10/site-packages/secretstorage/collection.py", line 44, in __init__
    self._collection.get_property('Label')
  File "/usr/lib/python3.10/site-packages/secretstorage/util.py", line 64, in get_property
    (signature, value), = self.send_and_get_reply(msg)
  File "/usr/lib/python3.10/site-packages/secretstorage/util.py", line 49, in send_and_get_reply
    raise ItemNotFoundException('Item does not exist!') from resp
secretstorage.exceptions.ItemNotFoundException: Item does not exist!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/keyring/backends/SecretService.py", line 61, in get_preferred_collec
tion
    collection = secretstorage.get_default_collection(bus)
  File "/usr/lib/python3.10/site-packages/secretstorage/collection.py", line 163, in get_default_collection
    return create_collection(connection, 'Default',
File "/usr/lib/python3.10/site-packages/secretstorage/collection.py", line 145, in create_collection
    raise PromptDismissedException('Prompt dismissed.')
secretstorage.exceptions.PromptDismissedException: Prompt dismissed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hungz/.local/share/nvim/site/pack/packer/start/gkeep.nvim/rplugin/python3/gkeep/plugin.py", line
 46, in d
    return f(self, *args[0])
  File "/home/hungz/.local/share/nvim/site/pack/packer/start/gkeep.nvim/rplugin/python3/gkeep/plugin.py", line
 80, in w
    f(self, *args, **kwargs)
  File "/home/hungz/.local/share/nvim/site/pack/packer/start/gkeep.nvim/rplugin/python3/gkeep/plugin.py", line
 361, in close_prompt
    self._modal.prompt.close(text)
  File "/home/hungz/.local/share/nvim/site/pack/packer/start/gkeep.nvim/rplugin/python3/gkeep/modal/prompt.py"
, line 66, in close
callback(text)
  File "/home/hungz/.local/share/nvim/site/pack/packer/start/gkeep.nvim/rplugin/python3/gkeep/plugin.py", line
 80, in w
    f(self, *args, **kwargs)
  File "/home/hungz/.local/share/nvim/site/pack/packer/start/gkeep.nvim/rplugin/python3/gkeep/plugin.py", line
 47, in d
    return f(self, *args)
  File "/home/hungz/.local/share/nvim/site/pack/packer/start/gkeep.nvim/rplugin/python3/gkeep/plugin.py", line
 621, in cmd_login
    token = keyring.get_password("google-keep-token", email)
  File "/usr/lib/python3.10/site-packages/keyring/core.py", line 55, in get_password
    return get_keyring().get_password(service_name, username)
  File "/usr/lib/python3.10/site-packages/keyring/backends/chainer.py", line 51, in get_password
    password = keyring.get_password(service, username)
  File "/usr/lib/python3.10/site-packages/keyring/backends/SecretService.py", line 78, in get_password
    collection = self.get_preferred_collection()
  File "/usr/lib/python3.10/site-packages/keyring/backends/SecretService.py", line 63, in get_preferred_collec
tion
    raise InitError("Failed to create the collection: %s." % e)

keyring.errors.InitError: Failed to create the collection: Prompt dismissed..
```

**Expected behavior**
Login success

**Version information**
 - OS: Arch Linux 
 - Neovim: 
 ```NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5
Compiled by builduser
```

 - Gkeep: [output of `:checkhealth gkeep`]
 ```
 gkeep: health#gkeep#check                            
    8 ========================================================================
  ## gkeep                                             
     - OK: gkeepapi 0.13.7 installed                    
     - OK: keyring installed                            
     - WARNING: Not logged in                           
       - ADVICE:                                        
         - Try :GkeepLogin                              
     - ERROR: Error with keyring provider: Failed to create the collection: Prompt dismissed..
     - INFO: Log file: /home/hungz/.cache/nvim/gkeep.log           
```
**Additional context**

**Screenshots**

**Comment by stevearc** [comment]
Check out the section of the readme under ["a note about keyring"](https://github.com/stevearc/gkeep.nvim#installation). The [keyring](https://github.com/jaraco/keyring) repo itself will have more details about what it needs in order to function. It works by default on most desktop operating systems, but getting it working when it doesn't is outside the scope of gkeep.
